ALTER TABLE skill_asset ADD COLUMN IF NOT EXISTS namespace_id BIGINT;
ALTER TABLE skill_asset ADD COLUMN IF NOT EXISTS slug VARCHAR(128);
ALTER TABLE skill_asset ADD COLUMN IF NOT EXISTS license_key VARCHAR(128);
ALTER TABLE skill_asset ADD COLUMN IF NOT EXISTS runtime_summary JSONB NOT NULL DEFAULT '{}'::jsonb;

CREATE TABLE IF NOT EXISTS skill_namespace (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    namespace_key VARCHAR(128) NOT NULL,
    display_name VARCHAR(256) NOT NULL,
    owner_scope_id BIGINT NOT NULL REFERENCES governance_scope (id),
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    created_by VARCHAR(128) NOT NULL,
    created_at TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_skill_namespace_key UNIQUE (namespace_key)
);

INSERT INTO skill_namespace (namespace_key, display_name, owner_scope_id, status, created_by)
SELECT 'skillhub', 'SKILL HUB', gs.id, 'ACTIVE', 'bootstrap'
FROM governance_scope gs
WHERE gs.scope_type = 'COMPANY' AND gs.scope_key = 'skillhub'
  AND NOT EXISTS (SELECT 1 FROM skill_namespace WHERE namespace_key = 'skillhub');

UPDATE skill_asset sa
SET namespace_id = sn.id,
    slug = COALESCE(sa.slug, sa.asset_key)
FROM skill_namespace sn
WHERE sn.namespace_key = 'skillhub' AND (sa.namespace_id IS NULL OR sa.slug IS NULL);

ALTER TABLE skill_asset ADD CONSTRAINT fk_skill_asset_namespace
    FOREIGN KEY (namespace_id) REFERENCES skill_namespace (id);
CREATE UNIQUE INDEX IF NOT EXISTS uk_skill_asset_namespace_slug
    ON skill_asset (namespace_id, slug) WHERE namespace_id IS NOT NULL AND slug IS NOT NULL;

CREATE TABLE IF NOT EXISTS skill_namespace_member (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    namespace_id BIGINT NOT NULL REFERENCES skill_namespace (id),
    principal_id BIGINT NOT NULL REFERENCES principal_account (id),
    role_key VARCHAR(16) NOT NULL,
    created_by VARCHAR(128) NOT NULL,
    created_at TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_skill_namespace_member UNIQUE (namespace_id, principal_id),
    CONSTRAINT ck_skill_namespace_role CHECK (role_key IN ('OWNER', 'ADMIN', 'MEMBER'))
);

INSERT INTO skill_namespace_member (namespace_id, principal_id, role_key, created_by)
SELECT sn.id, pa.id, CASE WHEN pa.username = 'admin' THEN 'OWNER' ELSE 'MEMBER' END, 'bootstrap'
FROM skill_namespace sn CROSS JOIN principal_account pa
WHERE sn.namespace_key = 'skillhub' AND pa.username IN ('admin', 'user')
  AND NOT EXISTS (
      SELECT 1 FROM skill_namespace_member existing
      WHERE existing.namespace_id = sn.id AND existing.principal_id = pa.id
  );

ALTER TABLE skill_version_manifest ADD COLUMN IF NOT EXISTS size_bytes BIGINT;
ALTER TABLE skill_version_manifest ADD COLUMN IF NOT EXISTS media_type VARCHAR(128);

CREATE TABLE IF NOT EXISTS skill_version_tag (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id BIGINT NOT NULL REFERENCES skill_asset (id),
    tag_name VARCHAR(64) NOT NULL,
    version_digest CHAR(64) NOT NULL,
    created_by VARCHAR(128) NOT NULL,
    created_at TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_skill_version_tag UNIQUE (asset_id, tag_name)
);

CREATE TABLE IF NOT EXISTS skill_version_tag_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id BIGINT NOT NULL REFERENCES skill_asset (id),
    tag_name VARCHAR(64) NOT NULL,
    previous_version_digest CHAR(64),
    next_version_digest CHAR(64),
    changed_by VARCHAR(128) NOT NULL,
    changed_at TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS skill_review_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version_digest CHAR(64) NOT NULL,
    applicant_id VARCHAR(128) NOT NULL,
    reviewer_id VARCHAR(128),
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    review_comment VARCHAR(2048),
    submitted_at TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reviewed_at TIMESTAMP(3) WITH TIME ZONE,
    CONSTRAINT ck_skill_review_status CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'WITHDRAWN'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_skill_review_pending
    ON skill_review_task (version_digest) WHERE status = 'PENDING';
CREATE INDEX IF NOT EXISTS idx_skill_namespace_member_principal
    ON skill_namespace_member (principal_id, namespace_id);
CREATE INDEX IF NOT EXISTS idx_skill_version_tag_digest
    ON skill_version_tag (version_digest);
CREATE INDEX IF NOT EXISTS idx_skill_review_version_status
    ON skill_review_task (version_digest, status);
