CREATE TABLE api_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    principal_id BIGINT NOT NULL REFERENCES principal_account (id),
    name VARCHAR(64) NOT NULL,
    token_prefix VARCHAR(16) NOT NULL,
    token_hash CHAR(64) NOT NULL,
    scope_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    expires_at TIMESTAMP(3) WITH TIME ZONE,
    last_used_at TIMESTAMP(3) WITH TIME ZONE,
    revoked_at TIMESTAMP(3) WITH TIME ZONE,
    created_at TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_api_token_hash UNIQUE (token_hash)
);

CREATE UNIQUE INDEX uk_api_token_principal_name_active
    ON api_token (principal_id, lower(name))
    WHERE revoked_at IS NULL;

CREATE INDEX idx_api_token_principal_status
    ON api_token (principal_id, revoked_at, created_at DESC);
