-- Skill execution analysis: expected-step contract per (slug, version) and
-- cached analysis results (problem rules, coverage, similarity conflicts, path cost).
--
-- Design notes:
--  * contract is parsed once per (slug, version_label) and reused by every trace.
--  * analysis rows are keyed by (slug, version_label, analysis_type, scope_key) so a
--    recompute overwrites instead of appending, and LLM verdicts are never paid twice.

CREATE TABLE skill_contract (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(128) NOT NULL,
    version_label VARCHAR(64) NOT NULL DEFAULT '',
    source_path VARCHAR(512),
    raw_hash CHAR(64),
    contract JSONB NOT NULL DEFAULT '{}'::jsonb,
    parse_method VARCHAR(16) NOT NULL DEFAULT 'rule',
    parse_meta JSONB,
    created_at TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_skill_contract UNIQUE (slug, version_label)
);

-- analysis_type: problem_rule | coverage | llm_verdict | conflict | path_cost
CREATE TABLE skill_analysis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(128) NOT NULL,
    version_label VARCHAR(64) NOT NULL DEFAULT '',
    analysis_type VARCHAR(24) NOT NULL,
    scope_key VARCHAR(192) NOT NULL,
    result JSONB NOT NULL DEFAULT '{}'::jsonb,
    status VARCHAR(16) NOT NULL DEFAULT 'ok',
    created_at TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_skill_analysis UNIQUE (slug, version_label, analysis_type, scope_key)
);

CREATE INDEX idx_skill_analysis_lookup ON skill_analysis(slug, version_label, analysis_type);
CREATE INDEX idx_skill_contract_lookup ON skill_contract(slug, version_label);

-- Detection reads one turn's steps in order; the unique key covers (turn_id, step_id)
-- but ordering queries need (turn_id, seq).
CREATE INDEX idx_observation_step_turn_seq ON observation_step(turn_id, seq);
CREATE INDEX idx_observation_step_skill_type ON observation_step(skill_slug, type);
