CREATE TABLE runtime_integration_instance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    integration_id VARCHAR(128) NOT NULL,
    scope_id BIGINT NOT NULL REFERENCES governance_scope (id),
    runtime_key VARCHAR(64) NOT NULL,
    runtime_version VARCHAR(64) NOT NULL,
    target_key CHAR(64) NOT NULL,
    adapter_version VARCHAR(64) NOT NULL,
    configuration_digest CHAR(64) NOT NULL,
    installation_state VARCHAR(32) NOT NULL,
    health_status VARCHAR(32) NOT NULL DEFAULT 'UNKNOWN',
    last_event_sequence INT NOT NULL DEFAULT 0,
    failure_stage VARCHAR(64),
    error_code VARCHAR(64),
    error_reason VARCHAR(2048),
    last_reported_at TIMESTAMP(3) WITH TIME ZONE,
    created_by VARCHAR(128) NOT NULL,
    updated_by VARCHAR(128) NOT NULL,
    created_at TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    row_version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_runtime_integration_id UNIQUE (integration_id),
    CONSTRAINT uk_runtime_integration_target UNIQUE (scope_id, runtime_key, target_key),
    CONSTRAINT ck_runtime_integration_target_digest CHECK (target_key ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_runtime_integration_config_digest CHECK (configuration_digest ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_runtime_integration_sequence CHECK (last_event_sequence >= 0),
    CONSTRAINT ck_runtime_integration_state CHECK (installation_state IN (
        'DETECTED', 'PLANNED', 'SNAPSHOTTED', 'APPLYING', 'VERIFYING', 'ACTIVE',
        'ACTION_REQUIRED', 'ROLLING_BACK', 'RESTORED', 'FAILED', 'REQUIRES_MANUAL', 'DISABLED'
    )),
    CONSTRAINT ck_runtime_integration_health CHECK (health_status IN (
        'UNKNOWN', 'HEALTHY', 'DEGRADED', 'UNHEALTHY'
    ))
);

CREATE TABLE runtime_integration_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id VARCHAR(128) NOT NULL,
    runtime_integration_instance_id BIGINT NOT NULL REFERENCES runtime_integration_instance (id),
    event_sequence INT NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    stage VARCHAR(64) NOT NULL,
    result VARCHAR(32) NOT NULL,
    installation_state VARCHAR(32) NOT NULL,
    health_status VARCHAR(32) NOT NULL,
    failure_stage VARCHAR(64),
    error_code VARCHAR(64),
    error_reason VARCHAR(2048),
    occurred_at TIMESTAMP(3) WITH TIME ZONE NOT NULL,
    received_at TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_runtime_integration_event_id UNIQUE (event_id),
    CONSTRAINT uk_runtime_integration_event_sequence UNIQUE (
        runtime_integration_instance_id, event_sequence
    ),
    CONSTRAINT ck_runtime_integration_event_sequence CHECK (event_sequence > 0),
    CONSTRAINT ck_runtime_integration_event_result CHECK (result IN (
        'SUCCEEDED', 'FAILED', 'ACTION_REQUIRED', 'REQUIRES_MANUAL'
    ))
);

CREATE INDEX idx_runtime_integration_scope_status
    ON runtime_integration_instance (scope_id, health_status, updated_at DESC, id DESC);

CREATE INDEX idx_runtime_integration_runtime_status
    ON runtime_integration_instance (runtime_key, installation_state, updated_at DESC, id DESC);

CREATE INDEX idx_runtime_integration_event_instance
    ON runtime_integration_event (runtime_integration_instance_id, event_sequence DESC);

CREATE TRIGGER trg_runtime_integration_event_append_only
BEFORE UPDATE OR DELETE ON runtime_integration_event
FOR EACH ROW EXECUTE FUNCTION prevent_governance_record_mutation();
