CREATE TABLE telemetry_ingest_batch (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id VARCHAR(128) NOT NULL,
    actor_id VARCHAR(128) NOT NULL,
    token_id VARCHAR(128) NOT NULL,
    scope_id BIGINT NOT NULL REFERENCES governance_scope (id),
    runtime_key VARCHAR(64) NOT NULL,
    payload_digest CHAR(64) NOT NULL,
    received_count INT NOT NULL,
    accepted_count INT NOT NULL DEFAULT 0,
    duplicate_count INT NOT NULL DEFAULT 0,
    rejected_count INT NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL,
    error_summary JSONB NOT NULL DEFAULT '{}'::jsonb,
    received_at TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP(3) WITH TIME ZONE,
    CONSTRAINT uk_telemetry_batch_request UNIQUE (request_id),
    CONSTRAINT ck_telemetry_batch_payload_digest CHECK (payload_digest ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_telemetry_batch_counts CHECK (
        received_count >= 0 AND accepted_count >= 0 AND duplicate_count >= 0 AND rejected_count >= 0
    )
);

CREATE TABLE runtime_event_dedup (
    event_id VARCHAR(128) PRIMARY KEY,
    batch_id BIGINT NOT NULL REFERENCES telemetry_ingest_batch (id),
    occurred_at TIMESTAMP(3) WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE runtime_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    event_id VARCHAR(128) NOT NULL,
    batch_id BIGINT NOT NULL REFERENCES telemetry_ingest_batch (id),
    schema_version VARCHAR(32) NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    scope_id BIGINT NOT NULL REFERENCES governance_scope (id),
    runtime_key VARCHAR(64) NOT NULL,
    runtime_version VARCHAR(64) NOT NULL,
    tracker_version VARCHAR(64),
    session_id VARCHAR(128) NOT NULL,
    trace_id VARCHAR(128) NOT NULL,
    span_id VARCHAR(128) NOT NULL,
    parent_span_id VARCHAR(128),
    sequence BIGINT NOT NULL,
    agent_id VARCHAR(128),
    parent_agent_id VARCHAR(128),
    model_name VARCHAR(128),
    tool_name VARCHAR(128),
    mcp_server VARCHAR(128),
    skill_name VARCHAR(128),
    version_digest CHAR(64),
    invocation_id VARCHAR(128),
    trigger_type VARCHAR(64),
    status VARCHAR(32) NOT NULL,
    duration_ms BIGINT,
    input_tokens BIGINT,
    output_tokens BIGINT,
    cost NUMERIC(20,8),
    version_unknown BOOLEAN NOT NULL DEFAULT FALSE,
    version_unknown_reason VARCHAR(256),
    attributes JSONB NOT NULL DEFAULT '{}'::jsonb,
    missing_fields JSONB NOT NULL DEFAULT '[]'::jsonb,
    privacy_actions JSONB NOT NULL DEFAULT '[]'::jsonb,
    occurred_at TIMESTAMP(3) WITH TIME ZONE NOT NULL,
    received_at TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (occurred_at, id),
    CONSTRAINT ck_runtime_event_sequence CHECK (sequence >= 0),
    CONSTRAINT ck_runtime_event_duration CHECK (duration_ms IS NULL OR duration_ms >= 0),
    CONSTRAINT ck_runtime_event_tokens CHECK (
        (input_tokens IS NULL OR input_tokens >= 0) AND (output_tokens IS NULL OR output_tokens >= 0)
    ),
    CONSTRAINT ck_runtime_event_version CHECK (
        (version_unknown = TRUE AND version_digest IS NULL AND version_unknown_reason IS NOT NULL)
        OR (version_unknown = FALSE AND version_digest ~ '^[0-9a-f]{64}$')
    )
) PARTITION BY RANGE (occurred_at);

DO $$
DECLARE
    partition_month DATE;
    next_month DATE;
    partition_name TEXT;
    month_offset INT;
BEGIN
    FOR month_offset IN 0..2 LOOP
        partition_month := (
            date_trunc('month', CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
            + (month_offset || ' month')::INTERVAL
        )::DATE;
        next_month := (partition_month + INTERVAL '1 month')::DATE;
        partition_name := 'runtime_event_' || to_char(partition_month, 'YYYY_MM');
        EXECUTE format(
            'CREATE TABLE %I PARTITION OF runtime_event FOR VALUES FROM (%L) TO (%L)',
            partition_name,
            partition_month::TEXT || ' 00:00:00+00',
            next_month::TEXT || ' 00:00:00+00'
        );
    END LOOP;
END $$;

CREATE INDEX idx_runtime_event_scope_time
    ON runtime_event (scope_id, occurred_at DESC, event_id);
CREATE INDEX idx_runtime_event_trace_time
    ON runtime_event (scope_id, trace_id, occurred_at, event_id);
CREATE INDEX idx_runtime_event_invocation_time
    ON runtime_event (scope_id, invocation_id, occurred_at, event_id)
    WHERE invocation_id IS NOT NULL;
CREATE INDEX idx_runtime_event_version_time
    ON runtime_event (scope_id, version_digest, occurred_at DESC, event_id)
    WHERE version_digest IS NOT NULL;

CREATE TRIGGER trg_runtime_event_append_only
BEFORE UPDATE OR DELETE ON runtime_event
FOR EACH ROW EXECUTE FUNCTION prevent_governance_record_mutation();

CREATE TABLE agent_trace (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope_id BIGINT NOT NULL REFERENCES governance_scope (id),
    trace_id VARCHAR(128) NOT NULL,
    session_id VARCHAR(128) NOT NULL,
    runtime_key VARCHAR(64) NOT NULL,
    runtime_version VARCHAR(64) NOT NULL,
    agent_id VARCHAR(128),
    parent_agent_id VARCHAR(128),
    status VARCHAR(32) NOT NULL,
    event_count INT NOT NULL DEFAULT 0,
    started_at TIMESTAMP(3) WITH TIME ZONE NOT NULL,
    ended_at TIMESTAMP(3) WITH TIME ZONE,
    completeness JSONB NOT NULL DEFAULT '{}'::jsonb,
    updated_at TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    row_version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_agent_trace_scope UNIQUE (scope_id, trace_id)
);

CREATE INDEX idx_agent_trace_scope_time
    ON agent_trace (scope_id, started_at DESC, trace_id);

CREATE TABLE skill_invocation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope_id BIGINT NOT NULL REFERENCES governance_scope (id),
    invocation_id VARCHAR(128) NOT NULL,
    trace_id VARCHAR(128) NOT NULL,
    span_id VARCHAR(128) NOT NULL,
    parent_span_id VARCHAR(128),
    runtime_key VARCHAR(64) NOT NULL,
    skill_name VARCHAR(128),
    version_digest CHAR(64),
    version_unknown BOOLEAN NOT NULL DEFAULT FALSE,
    version_unknown_reason VARCHAR(256),
    tracker_version VARCHAR(64),
    trigger_type VARCHAR(64),
    status VARCHAR(32) NOT NULL,
    duration_ms BIGINT,
    input_tokens BIGINT,
    output_tokens BIGINT,
    cost NUMERIC(20,8),
    occurred_at TIMESTAMP(3) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_skill_invocation_scope UNIQUE (scope_id, invocation_id),
    CONSTRAINT ck_skill_invocation_version CHECK (
        (version_unknown = TRUE AND version_digest IS NULL AND version_unknown_reason IS NOT NULL)
        OR (version_unknown = FALSE AND version_digest ~ '^[0-9a-f]{64}$')
    )
);

CREATE INDEX idx_skill_invocation_scope_time
    ON skill_invocation (scope_id, occurred_at DESC, invocation_id);
CREATE INDEX idx_skill_invocation_version_time
    ON skill_invocation (scope_id, version_digest, occurred_at DESC, invocation_id)
    WHERE version_digest IS NOT NULL;
CREATE INDEX idx_skill_invocation_trace_time
    ON skill_invocation (scope_id, trace_id, occurred_at, invocation_id);

CREATE TABLE metric_aggregate (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope_id BIGINT NOT NULL REFERENCES governance_scope (id),
    metric_key VARCHAR(128) NOT NULL,
    definition_version VARCHAR(64) NOT NULL,
    window_start TIMESTAMP(3) WITH TIME ZONE NOT NULL,
    window_end TIMESTAMP(3) WITH TIME ZONE NOT NULL,
    dimension_digest CHAR(64) NOT NULL,
    dimensions JSONB NOT NULL DEFAULT '{}'::jsonb,
    sample_count BIGINT NOT NULL DEFAULT 0,
    success_count BIGINT NOT NULL DEFAULT 0,
    error_count BIGINT NOT NULL DEFAULT 0,
    numerator NUMERIC(24,8),
    denominator NUMERIC(24,8),
    input_tokens BIGINT NOT NULL DEFAULT 0,
    output_tokens BIGINT NOT NULL DEFAULT 0,
    total_cost NUMERIC(24,8) NOT NULL DEFAULT 0,
    latency_sum_ms BIGINT NOT NULL DEFAULT 0,
    latency_max_ms BIGINT NOT NULL DEFAULT 0,
    completeness_status VARCHAR(32) NOT NULL,
    updated_at TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_metric_window_dimensions UNIQUE (
        scope_id, metric_key, definition_version, window_start, window_end, dimension_digest
    ),
    CONSTRAINT ck_metric_window CHECK (window_end > window_start)
);

CREATE INDEX idx_metric_scope_window
    ON metric_aggregate (scope_id, metric_key, window_start DESC, window_end);

CREATE TABLE telemetry_aggregation_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id VARCHAR(160) NOT NULL,
    batch_id BIGINT NOT NULL REFERENCES telemetry_ingest_batch (id),
    event_type VARCHAR(64) NOT NULL,
    payload JSONB NOT NULL,
    delivery_state VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    attempts INT NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delivered_at TIMESTAMP(3) WITH TIME ZONE,
    created_at TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_telemetry_outbox_event UNIQUE (event_id)
);

CREATE INDEX idx_telemetry_outbox_delivery
    ON telemetry_aggregation_outbox (delivery_state, next_attempt_at, id);

CREATE TABLE telemetry_aggregation_checkpoint (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    consumer_key VARCHAR(128) NOT NULL,
    last_batch_id BIGINT,
    window_start TIMESTAMP(3) WITH TIME ZONE,
    window_end TIMESTAMP(3) WITH TIME ZONE,
    updated_at TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    row_version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_telemetry_checkpoint_consumer UNIQUE (consumer_key)
);

CREATE INDEX idx_telemetry_batch_scope_time
    ON telemetry_ingest_batch (scope_id, received_at DESC, id DESC);
CREATE INDEX idx_runtime_event_dedup_created
    ON runtime_event_dedup (created_at, event_id);
