CREATE TABLE principal_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(128) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_principal_account_username UNIQUE (username)
);

CREATE TABLE governance_scope (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope_type VARCHAR(32) NOT NULL,
    scope_key VARCHAR(128) NOT NULL,
    name VARCHAR(256) NOT NULL,
    parent_scope_id BIGINT,
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    source_system VARCHAR(64),
    source_id VARCHAR(128),
    created_at TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_scope_type_key UNIQUE (scope_type, scope_key),
    CONSTRAINT fk_scope_parent FOREIGN KEY (parent_scope_id) REFERENCES governance_scope (id)
);

CREATE TABLE principal_scope_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    principal_id BIGINT NOT NULL REFERENCES principal_account (id),
    scope_id BIGINT NOT NULL REFERENCES governance_scope (id),
    role_key VARCHAR(64) NOT NULL,
    created_at TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_principal_scope_role UNIQUE (principal_id, scope_id, role_key)
);

CREATE INDEX idx_scope_parent ON governance_scope (parent_scope_id);
CREATE INDEX idx_scope_role ON principal_scope_role (scope_id, role_key);
