CREATE TABLE skill (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(128) NOT NULL UNIQUE,
    name VARCHAR(128) NOT NULL,
    description VARCHAR(2048) NOT NULL,
    category VARCHAR(128) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_skill_status CHECK (status IN ('ACTIVE', 'OFFLINE'))
);

CREATE TABLE skill_version (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    skill_id BIGINT NOT NULL REFERENCES skill(id) ON DELETE CASCADE,
    version_label VARCHAR(64) NOT NULL,
    version_digest CHAR(64) NOT NULL UNIQUE,
    created_at TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_skill_version UNIQUE (skill_id, version_label)
);

CREATE TABLE skill_file (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version_id BIGINT NOT NULL REFERENCES skill_version(id) ON DELETE CASCADE,
    path VARCHAR(512) NOT NULL,
    content BYTEA NOT NULL,
    content_type VARCHAR(128) NOT NULL,
    size_bytes BIGINT NOT NULL,
    content_digest CHAR(64) NOT NULL,
    CONSTRAINT uk_skill_file UNIQUE (version_id, path)
);

CREATE INDEX idx_skill_category_status ON skill(category, status);
CREATE INDEX idx_skill_version_created ON skill_version(skill_id, created_at DESC);
