CREATE TABLE skill_asset (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_key VARCHAR(128) NOT NULL,
    name VARCHAR(128) NOT NULL,
    description VARCHAR(2048) NOT NULL,
    owner_scope_id BIGINT NOT NULL REFERENCES governance_scope (id),
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    created_by VARCHAR(128) NOT NULL,
    updated_by VARCHAR(128) NOT NULL,
    created_at TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    row_version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_asset_key UNIQUE (asset_key)
);

CREATE TABLE skill_import_attempt (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id VARCHAR(128) NOT NULL,
    asset_id BIGINT REFERENCES skill_asset (id),
    source_type VARCHAR(32) NOT NULL,
    source_locator VARCHAR(1024) NOT NULL,
    status VARCHAR(32) NOT NULL,
    failure_stage VARCHAR(32),
    failure_code VARCHAR(64),
    failure_reason VARCHAR(2048),
    artifact_digest CHAR(64),
    created_by VARCHAR(128) NOT NULL,
    created_at TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_import_request_id UNIQUE (request_id)
);

CREATE TABLE skill_artifact (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id BIGINT NOT NULL REFERENCES skill_asset (id),
    artifact_uri VARCHAR(1024) NOT NULL,
    artifact_digest CHAR(64) NOT NULL,
    media_type VARCHAR(128) NOT NULL,
    size_bytes BIGINT NOT NULL,
    source_snapshot_uri VARCHAR(1024),
    encryption_status VARCHAR(32) NOT NULL DEFAULT 'UNKNOWN',
    created_by VARCHAR(128) NOT NULL,
    created_at TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_artifact_digest UNIQUE (artifact_digest)
);

CREATE TABLE skill_version (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id BIGINT NOT NULL REFERENCES skill_asset (id),
    artifact_id BIGINT NOT NULL REFERENCES skill_artifact (id),
    version_label VARCHAR(64) NOT NULL,
    version_digest CHAR(64) NOT NULL,
    source_type VARCHAR(32) NOT NULL,
    source_locator VARCHAR(1024) NOT NULL,
    source_snapshot_uri VARCHAR(1024),
    metadata_status VARCHAR(32) NOT NULL,
    lifecycle_state VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    created_by VARCHAR(128) NOT NULL,
    created_at TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_asset_version_label UNIQUE (asset_id, version_label),
    CONSTRAINT uk_version_digest UNIQUE (version_digest)
);

CREATE TABLE skill_version_manifest (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version_id BIGINT NOT NULL REFERENCES skill_version (id),
    path VARCHAR(512) NOT NULL,
    required BOOLEAN NOT NULL,
    read_status VARCHAR(32) NOT NULL,
    content_digest CHAR(64),
    created_at TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_version_manifest UNIQUE (version_id, path)
);

CREATE TABLE skill_dependency (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version_id BIGINT NOT NULL REFERENCES skill_version (id),
    dependency_key VARCHAR(128) NOT NULL,
    version_constraint VARCHAR(128),
    status VARCHAR(32) NOT NULL,
    CONSTRAINT uk_version_dependency UNIQUE (version_id, dependency_key)
);

CREATE TABLE runtime_definition (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    runtime_key VARCHAR(64) NOT NULL,
    runtime_version VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    capabilities JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_runtime_key_version UNIQUE (runtime_key, runtime_version)
);

CREATE TABLE skill_runtime_compatibility (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version_id BIGINT NOT NULL REFERENCES skill_version (id),
    runtime_id BIGINT NOT NULL REFERENCES runtime_definition (id),
    support_status VARCHAR(32) NOT NULL,
    reason VARCHAR(2048),
    CONSTRAINT uk_version_runtime UNIQUE (version_id, runtime_id)
);

CREATE INDEX idx_owner_scope_status ON skill_asset (owner_scope_id, status);
CREATE INDEX idx_import_asset_time ON skill_import_attempt (asset_id, created_at DESC);
CREATE INDEX idx_version_asset_state ON skill_version (asset_id, lifecycle_state, created_at DESC);
CREATE INDEX idx_required_read_status ON skill_version_manifest (required, read_status);
