CREATE TABLE release_policy_version (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope_type VARCHAR(32) NOT NULL,
    scope_id BIGINT NOT NULL REFERENCES governance_scope (id),
    policy_version VARCHAR(64) NOT NULL,
    effective_at TIMESTAMP(3) WITH TIME ZONE NOT NULL,
    minimum_valid_cases INT NOT NULL DEFAULT 30,
    gray_ratio DECIMAL(5,4) NOT NULL DEFAULT 0.1000,
    observation_window_seconds BIGINT NOT NULL DEFAULT 86400,
    minimum_valid_calls INT NOT NULL DEFAULT 30,
    rollback_conditions JSONB NOT NULL DEFAULT '{}'::jsonb,
    auto_release_conditions JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_by VARCHAR(128) NOT NULL,
    created_at TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_policy_scope_version UNIQUE (scope_type, scope_id, policy_version),
    CONSTRAINT ck_policy_gray_ratio CHECK (gray_ratio >= 0 AND gray_ratio <= 1),
    CONSTRAINT ck_policy_minimum_cases CHECK (minimum_valid_cases >= 0),
    CONSTRAINT ck_policy_minimum_calls CHECK (minimum_valid_calls >= 0)
);

CREATE TABLE retention_policy_version (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope_type VARCHAR(32) NOT NULL,
    scope_id BIGINT NOT NULL REFERENCES governance_scope (id),
    data_class VARCHAR(64) NOT NULL,
    retention_type VARCHAR(16) NOT NULL,
    retention_seconds BIGINT,
    policy_version VARCHAR(64) NOT NULL,
    effective_at TIMESTAMP(3) WITH TIME ZONE NOT NULL,
    approved_by VARCHAR(128) NOT NULL,
    created_by VARCHAR(128) NOT NULL,
    created_at TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_retention_scope_type_version UNIQUE (scope_type, scope_id, data_class, policy_version),
    CONSTRAINT ck_retention_seconds CHECK (
        (retention_type = 'PERMANENT' AND retention_seconds IS NULL)
        OR (retention_type = 'DURATION' AND retention_seconds > 0)
    )
);

CREATE TABLE release_binding (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id BIGINT NOT NULL REFERENCES skill_asset (id),
    version_digest CHAR(64) NOT NULL,
    scope_type VARCHAR(32) NOT NULL,
    scope_id BIGINT NOT NULL REFERENCES governance_scope (id),
    binding_state VARCHAR(32) NOT NULL,
    is_current BOOLEAN NOT NULL DEFAULT TRUE,
    policy_version VARCHAR(64) NOT NULL,
    decision_id BIGINT,
    effective_at TIMESTAMP(3) WITH TIME ZONE NOT NULL,
    released_at TIMESTAMP(3) WITH TIME ZONE NOT NULL,
    created_by VARCHAR(128) NOT NULL,
    created_at TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX uk_binding_scope_asset_current
    ON release_binding (asset_id, scope_type, scope_id)
    WHERE is_current = TRUE;

CREATE INDEX idx_binding_version_scope ON release_binding (version_digest, scope_type, scope_id);

CREATE TABLE gate_evidence (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version_digest CHAR(64) NOT NULL,
    evidence_type VARCHAR(32) NOT NULL,
    result VARCHAR(32) NOT NULL,
    producer_type VARCHAR(16) NOT NULL,
    producer_id VARCHAR(128) NOT NULL,
    evidence_uri VARCHAR(1024),
    evidence_digest CHAR(64),
    conditions JSONB NOT NULL DEFAULT '{}'::jsonb,
    generated_at TIMESTAMP(3) WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP(3) WITH TIME ZONE,
    created_at TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_evidence_digest UNIQUE (evidence_digest)
);

CREATE TABLE release_decision (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version_digest CHAR(64) NOT NULL,
    scope_type VARCHAR(32) NOT NULL,
    scope_id BIGINT NOT NULL REFERENCES governance_scope (id),
    policy_version VARCHAR(64) NOT NULL,
    release_mode VARCHAR(32) NOT NULL,
    decision_state VARCHAR(32) NOT NULL,
    matched_rules JSONB NOT NULL DEFAULT '[]'::jsonb,
    blocking_reasons JSONB NOT NULL DEFAULT '[]'::jsonb,
    request_id VARCHAR(128) NOT NULL,
    decided_at TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(128) NOT NULL,
    CONSTRAINT uk_decision_request_scope UNIQUE (request_id, scope_type, scope_id)
);

CREATE TABLE release_decision_evidence (
    decision_id BIGINT NOT NULL REFERENCES release_decision (id),
    evidence_id BIGINT NOT NULL REFERENCES gate_evidence (id),
    PRIMARY KEY (decision_id, evidence_id)
);

CREATE TABLE approval_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    decision_id BIGINT NOT NULL REFERENCES release_decision (id),
    applicant_id VARCHAR(128) NOT NULL,
    approver_id VARCHAR(128) NOT NULL,
    approval_state VARCHAR(32) NOT NULL,
    comment VARCHAR(2048),
    actor_type VARCHAR(16) NOT NULL,
    approved_at TIMESTAMP(3) WITH TIME ZONE,
    CONSTRAINT ck_approval_separation CHECK (applicant_id <> approver_id OR actor_type = 'SERVICE')
);

CREATE INDEX idx_policy_effective_at ON release_policy_version (scope_type, scope_id, effective_at DESC);
CREATE INDEX idx_retention_effective_at ON retention_policy_version (scope_type, scope_id, data_class, effective_at DESC);
CREATE INDEX idx_evidence_version_type ON gate_evidence (version_digest, evidence_type, generated_at DESC);
CREATE INDEX idx_decision_version_state ON release_decision (version_digest, decision_state, decided_at DESC);
