CREATE TABLE discovered_skill (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_type VARCHAR(32) NOT NULL,
    source_owner VARCHAR(128) NOT NULL,
    source_repository VARCHAR(128) NOT NULL,
    source_branch VARCHAR(128) NOT NULL DEFAULT 'main',
    source_path VARCHAR(512) NOT NULL DEFAULT '',
    source_url VARCHAR(1024) NOT NULL,
    install_url VARCHAR(1024) NOT NULL,
    package_type VARCHAR(16) NOT NULL DEFAULT 'SINGLE',
    name VARCHAR(256) NOT NULL,
    description VARCHAR(4096) NOT NULL,
    category VARCHAR(128) NOT NULL,
    supported_agents VARCHAR(1024),
    github_stars BIGINT NOT NULL DEFAULT 0,
    github_forks BIGINT NOT NULL DEFAULT 0,
    external_install_count BIGINT NOT NULL DEFAULT 0,
    discovery_download_count BIGINT NOT NULL DEFAULT 0,
    trend_score DOUBLE PRECISION NOT NULL DEFAULT 0,
    quality_score DOUBLE PRECISION NOT NULL DEFAULT 0,
    trust_level VARCHAR(32) NOT NULL DEFAULT 'COMMUNITY',
    license VARCHAR(128),
    source_updated_at TIMESTAMP(3) WITH TIME ZONE,
    last_synced_at TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sync_status VARCHAR(32) NOT NULL DEFAULT 'SYNCED',
    visibility_status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_discovered_skill_source UNIQUE (source_type, source_owner, source_repository, source_path),
    CONSTRAINT ck_discovered_skill_package_type CHECK (package_type IN ('SINGLE', 'COMPOSITE')),
    CONSTRAINT ck_discovered_skill_visibility CHECK (visibility_status IN ('ACTIVE', 'UNAVAILABLE')),
    CONSTRAINT ck_discovered_skill_sync_status CHECK (sync_status IN ('SYNCED', 'ERROR', 'PENDING'))
);

CREATE TABLE discovered_skill_file (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    discovered_skill_id BIGINT NOT NULL REFERENCES discovered_skill(id) ON DELETE CASCADE,
    path VARCHAR(1024) NOT NULL,
    source_url VARCHAR(2048) NOT NULL,
    content BYTEA,
    content_type VARCHAR(128) NOT NULL,
    size_bytes BIGINT NOT NULL DEFAULT 0,
    content_digest CHAR(64),
    is_binary BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_discovered_skill_file UNIQUE (discovered_skill_id, path)
);

CREATE TABLE discovery_sync_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_type VARCHAR(32) NOT NULL,
    source_key VARCHAR(512) NOT NULL,
    started_at TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finished_at TIMESTAMP(3) WITH TIME ZONE,
    status VARCHAR(32) NOT NULL,
    items_synced INTEGER NOT NULL DEFAULT 0,
    error_message VARCHAR(2048)
);

CREATE INDEX idx_discovered_skill_category_status ON discovered_skill(category, visibility_status);
CREATE INDEX idx_discovered_skill_sort ON discovered_skill(trend_score DESC, github_stars DESC, source_updated_at DESC);
CREATE INDEX idx_discovered_skill_file_skill ON discovered_skill_file(discovered_skill_id, path);
