CREATE TABLE governance_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_key VARCHAR(64) NOT NULL,
    name VARCHAR(128) NOT NULL,
    created_at TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_role_key UNIQUE (role_key)
);

CREATE TABLE audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id VARCHAR(128) NOT NULL,
    actor_type VARCHAR(16) NOT NULL,
    action VARCHAR(64) NOT NULL,
    object_type VARCHAR(64) NOT NULL,
    object_id VARCHAR(128) NOT NULL,
    before_state JSONB NOT NULL DEFAULT '{}'::jsonb,
    after_state JSONB NOT NULL DEFAULT '{}'::jsonb,
    reason VARCHAR(2048),
    scope_type VARCHAR(32),
    scope_id BIGINT,
    policy_version VARCHAR(64),
    occurred_at TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_audit_object_time ON audit_log (object_type, object_id, occurred_at DESC);
CREATE INDEX idx_audit_actor_time ON audit_log (actor_id, occurred_at DESC);
CREATE INDEX idx_audit_scope_time ON audit_log (scope_id, occurred_at DESC);
