CREATE TABLE observation_client (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id VARCHAR(128) NOT NULL UNIQUE,
    hostname VARCHAR(256),
    os VARCHAR(64),
    meta TEXT,
    first_seen_at TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen_at TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE observation_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_row_id BIGINT NOT NULL REFERENCES observation_client(id) ON DELETE CASCADE,
    session_key VARCHAR(256) NOT NULL,
    client_name VARCHAR(32) NOT NULL,
    started_at TIMESTAMP(3) WITH TIME ZONE,
    ended_at TIMESTAMP(3) WITH TIME ZONE,
    created_at TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_observation_session UNIQUE (client_row_id, session_key)
);

CREATE TABLE observation_turn (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL REFERENCES observation_session(id) ON DELETE CASCADE,
    turn_index INTEGER NOT NULL,
    started_at TIMESTAMP(3) WITH TIME ZONE,
    user_text TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_observation_turn UNIQUE (session_id, turn_index)
);

CREATE TABLE observation_step (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    turn_id BIGINT NOT NULL REFERENCES observation_turn(id) ON DELETE CASCADE,
    step_id VARCHAR(256) NOT NULL,
    seq INTEGER NOT NULL,
    type VARCHAR(16) NOT NULL,
    ts TIMESTAMP(3) WITH TIME ZONE,
    skill_slug VARCHAR(128),
    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_observation_step UNIQUE (turn_id, step_id),
    CONSTRAINT ck_observation_step_type CHECK (type IN ('user', 'skill', 'tool', 'document'))
);

CREATE TABLE observation_ingest_batch (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id VARCHAR(64) NOT NULL UNIQUE,
    client_id VARCHAR(128) NOT NULL,
    received_at TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    session_count INTEGER NOT NULL DEFAULT 0,
    turn_count INTEGER NOT NULL DEFAULT 0,
    step_count INTEGER NOT NULL DEFAULT 0,
    skipped_step_count INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX idx_observation_step_skill_ts ON observation_step(skill_slug, ts DESC);
CREATE INDEX idx_observation_step_type ON observation_step(type);
CREATE INDEX idx_observation_session_client_name ON observation_session(client_name, started_at DESC);
CREATE INDEX idx_observation_turn_session ON observation_turn(session_id, turn_index);
