CREATE TABLE installation_instance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id BIGINT NOT NULL REFERENCES skill_asset (id),
    current_version_digest CHAR(64),
    runtime_key VARCHAR(64) NOT NULL,
    runtime_version VARCHAR(64),
    target_type VARCHAR(32) NOT NULL,
    target_key VARCHAR(256) NOT NULL,
    scope_id BIGINT NOT NULL REFERENCES governance_scope (id),
    desired_state VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    skill_state VARCHAR(32) NOT NULL DEFAULT 'NOT_INSTALLED',
    tracker_state VARCHAR(32) NOT NULL DEFAULT 'NOT_INSTALLED',
    overall_state VARCHAR(32) NOT NULL DEFAULT 'UNAVAILABLE',
    health_status VARCHAR(32) NOT NULL DEFAULT 'UNKNOWN',
    last_health_at TIMESTAMP(3) WITH TIME ZONE,
    last_error_code VARCHAR(64),
    last_error_reason VARCHAR(2048),
    installed_at TIMESTAMP(3) WITH TIME ZONE,
    created_by VARCHAR(128) NOT NULL,
    updated_by VARCHAR(128) NOT NULL,
    created_at TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    row_version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_installation_target UNIQUE (asset_id, runtime_key, target_type, target_key, scope_id)
);

CREATE TABLE tracker_binding (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    installation_instance_id BIGINT NOT NULL REFERENCES installation_instance (id),
    tracker_key VARCHAR(128) NOT NULL,
    tracker_version VARCHAR(64) NOT NULL,
    configuration_digest CHAR(64),
    installation_state VARCHAR(32) NOT NULL DEFAULT 'NOT_INSTALLED',
    health_state VARCHAR(32) NOT NULL DEFAULT 'UNKNOWN',
    last_health_at TIMESTAMP(3) WITH TIME ZONE,
    last_error_code VARCHAR(64),
    last_error_reason VARCHAR(2048),
    created_by VARCHAR(128) NOT NULL,
    updated_by VARCHAR(128) NOT NULL,
    created_at TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    row_version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_tracker_instance_key UNIQUE (installation_instance_id, tracker_key)
);

CREATE TABLE installation_operation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation_id VARCHAR(128) NOT NULL,
    request_id VARCHAR(128) NOT NULL,
    operation_type VARCHAR(32) NOT NULL,
    installation_instance_id BIGINT NOT NULL REFERENCES installation_instance (id),
    asset_id BIGINT NOT NULL REFERENCES skill_asset (id),
    previous_version_digest CHAR(64),
    target_version_digest CHAR(64),
    runtime_key VARCHAR(64) NOT NULL,
    runtime_version VARCHAR(64),
    scope_id BIGINT NOT NULL REFERENCES governance_scope (id),
    operation_stage VARCHAR(32) NOT NULL DEFAULT 'REQUESTED',
    operation_state VARCHAR(32) NOT NULL DEFAULT 'REQUESTED',
    rollback_state VARCHAR(32) NOT NULL DEFAULT 'NOT_REQUIRED',
    failure_stage VARCHAR(32),
    error_code VARCHAR(64),
    error_reason VARCHAR(2048),
    actor_id VARCHAR(128) NOT NULL,
    requested_at TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at TIMESTAMP(3) WITH TIME ZONE,
    completed_at TIMESTAMP(3) WITH TIME ZONE,
    created_at TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    row_version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_installation_operation_id UNIQUE (operation_id),
    CONSTRAINT uk_installation_operation_request UNIQUE (request_id, installation_instance_id)
);

CREATE TABLE installation_operation_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id VARCHAR(128) NOT NULL,
    operation_id BIGINT NOT NULL REFERENCES installation_operation (id),
    event_sequence INT NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    event_state VARCHAR(32) NOT NULL,
    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    occurred_at TIMESTAMP(3) WITH TIME ZONE NOT NULL,
    received_at TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_installation_event_id UNIQUE (event_id),
    CONSTRAINT uk_installation_operation_sequence UNIQUE (operation_id, event_sequence)
);

CREATE INDEX idx_installation_scope_state
    ON installation_instance (scope_id, overall_state, updated_at DESC);
CREATE INDEX idx_installation_version
    ON installation_instance (current_version_digest, runtime_key);
CREATE INDEX idx_installation_operation_state
    ON installation_operation (operation_state, requested_at DESC);
CREATE INDEX idx_installation_operation_instance
    ON installation_operation (installation_instance_id, created_at DESC);
CREATE INDEX idx_installation_event_operation
    ON installation_operation_event (operation_id, event_sequence);
