import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { homedir, platform } from 'node:os'
import { atomicWriteFile } from './atomic.js'
import { hookCmdPath, observerNodePath, observerScriptPath } from './paths.js'
import { ensureStore } from './store.js'

interface HookItem {
  type?: string
  command?: string
  commandWindows?: string
  [key: string]: unknown
}

interface HookEntry {
  matcher?: string
  hooks?: HookItem[]
}

export interface HookSpec {
  command: string
  matcher?: string
}

const THIRD_PARTY = /hook-handler|skill-trace|cc-skill-trace/i
const LAUNCHER_PATH = /SkillHub[\\/]+observability[\\/]+bin[\\/]+hook\.(?:cmd|sh)/i
const LOOKS_LIKE_HOOK = /--phase/i
const OWNED_RUNTIME = [
  /skillhub-observer/i,
  /skill-hub-simple[\\/]+(?:cli[\\/]+)?observer[\\/]+dist[\\/]+index\.js/i,
  /@second196[\\/]+skillhub-observer/i
]

export function isOurObserverHook(command: string): boolean {
  const c = String(command || '')
  if (THIRD_PARTY.test(c)) return false
  if (LAUNCHER_PATH.test(c)) return true
  const looksLikeHook = LOOKS_LIKE_HOOK.test(c) || /hook\.(?:cmd|sh)\b/i.test(c)
  if (!looksLikeHook) return false
  return OWNED_RUNTIME.some((re) => re.test(c))
}

function isOurHookItem(item: HookItem): boolean {
  return isOurObserverHook(String(item.command || '')) || isOurObserverHook(String(item.commandWindows || ''))
}

export function rewriteEventHooks(
  entries: HookEntry[] | undefined,
  specs: HookSpec[]
): HookEntry[] {
  const kept = (Array.isArray(entries) ? entries : [])
    .map((entry) => ({
      ...entry,
      hooks: (entry.hooks || []).filter((hook) => !isOurHookItem(hook))
    }))
    .filter((entry) => (entry.hooks || []).length > 0)
  for (const spec of specs) {
    kept.push(spec.matcher
      ? { matcher: spec.matcher, hooks: [{ type: 'command', command: spec.command }] }
      : { hooks: [{ type: 'command', command: spec.command }] })
  }
  return kept
}

export async function installHooks(options: { serviceUrl?: string } = {}): Promise<string> {
  await ensureStore()
  const { saveConfig, defaultServiceUrl, parseServiceUrl } = await import('./config.js')
  const { installBootTasks } = await import('./schedule.js')
  const serviceUrl = options.serviceUrl || defaultServiceUrl()
  const parsed = parseServiceUrl(serviceUrl)
  const config = await saveConfig({
    serviceUrl,
    host: parsed?.host,
    port: parsed?.port,
    protocol: parsed?.protocol,
    bootTask: true
  })
  const launcher = await writeHookLauncher()
  const command = (phase: string, provider: string) => hookCommand(launcher, phase, provider)
  const lines: string[] = []
  lines.push(`已写入稳定 hook 入口: ${launcher.path}`)
  lines.push(await installClaude(command))
  lines.push(await installCodex(command))
  try {
    lines.push(await installBootTasks())
  } catch (error) {
    throw new Error(`hooks 已写入，但开机任务注册失败：${error instanceof Error ? error.message : String(error)}`)
  }
  const { spawnDrain } = await import('./drain.js')
  spawnDrain(['--reconcile'])
  lines.push('已在后台启动 drain --reconcile（不阻塞 install）')
  lines.push(`已写入 config.json，serviceUrl=${config.serviceUrl}`)
  lines.push(`后续改地址请执行: skillhub-observer config-set --host <ip> --port <port>`)
  lines.push(`日志: logs/observer.log`)
  return lines.join('\n')
}

function hookCommand(launcher: { path: string }, phase: string, provider: string): string {
  return `${quoteArg(launcher.path)} ${phase} ${provider}`
}

async function writeHookLauncher(): Promise<{ path: string; nodePath: string; scriptPath: string }> {
  const path = hookCmdPath()
  const nodePath = observerNodePath()
  const scriptPath = observerScriptPath()
  await mkdir(dirname(path), { recursive: true })
  if (platform() === 'win32') {
    const body = [
      '@echo off',
      'rem SkillHub Observer hook launcher. Generated by install; do not edit by hand.',
      `"${nodePath}" "${scriptPath}" hook --phase %1 --provider %2`,
      ''
    ].join('\r\n')
    await atomicWriteFile(path, body)
  } else {
    const body = [
      '#!/bin/sh',
      '# SkillHub Observer hook launcher. Generated by install; do not edit by hand.',
      `exec "${nodePath}" "${scriptPath}" hook --phase "$1" --provider "$2"`,
      ''
    ].join('\n')
    await atomicWriteFile(path, body, 0o755)
  }
  return { path, nodePath, scriptPath }
}

async function installClaude(command: (phase: string, provider: string) => string): Promise<string> {
  const settingsPath = join(homedir(), '.claude', 'settings.json')
  const settings = await readJson(settingsPath)
  const hooks = asRecord(settings.hooks)
  const cmd = (phase: string) => command(phase, 'claude-code')
  applyEvent(hooks, 'PreToolUse', [
    { command: cmd('pre'), matcher: 'Skill' },
    { command: cmd('pre'), matcher: 'Read|ReadFile' }
  ])
  applyEvent(hooks, 'PostToolUse', [
    { command: cmd('post'), matcher: 'Skill' },
    { command: cmd('post'), matcher: 'Read|ReadFile' }
  ])
  applyEvent(hooks, 'Stop', [{ command: cmd('stop') }])
  applyEvent(hooks, 'SessionEnd', [{ command: cmd('session-end') }])
  applyEvent(hooks, 'SessionStart', [{ command: cmd('session-start') }])
  settings.hooks = hooks
  await writeJson(settingsPath, settings)
  return `已写入 Claude Code hooks: ${settingsPath}`
}

async function installCodex(command: (phase: string, provider: string) => string): Promise<string> {
  const hooksPath = join(homedir(), '.codex', 'hooks.json')
  const settings = await readJson(hooksPath)
  const hooks = asRecord(settings.hooks)
  const cmd = (phase: string) => command(phase, 'codex')
  applyEvent(hooks, 'PreToolUse', [{ command: cmd('pre'), matcher: '*' }])
  applyEvent(hooks, 'PostToolUse', [{ command: cmd('post'), matcher: '*' }])
  applyEvent(hooks, 'Stop', [{ command: cmd('stop'), matcher: '*' }])
  applyEvent(hooks, 'SessionEnd', [{ command: cmd('session-end'), matcher: '*' }])
  applyEvent(hooks, 'SessionStart', [{ command: cmd('session-start'), matcher: '*' }])
  settings.hooks = hooks
  await writeJson(hooksPath, settings)
  const configNote = await enableCodexFeatureHooks()
  return `已写入 Codex hooks: ${hooksPath}\n${configNote}`
}

function applyEvent(hooks: Record<string, unknown>, event: string, specs: HookSpec[]): void {
  const entries = Array.isArray(hooks[event]) ? hooks[event] as HookEntry[] : []
  hooks[event] = rewriteEventHooks(entries, specs)
}

async function enableCodexFeatureHooks(): Promise<string> {
  const configPath = join(homedir(), '.codex', 'config.toml')
  let text = ''
  try {
    text = await readFile(configPath, 'utf8')
  } catch {
    await mkdir(dirname(configPath), { recursive: true })
    await writeFile(configPath, '[features]\nhooks = true\n', 'utf8')
    return `已创建 ${configPath} 并启用 [features].hooks`
  }
  if (/^\s*hooks\s*=/m.test(text)) {
    const next = text.replace(/^\s*hooks\s*=\s*.*$/m, 'hooks = true')
    if (next !== text) await writeFile(configPath, next, 'utf8')
    return `已在 ${configPath} 启用 [features].hooks`
  }
  if (/\[features\]/.test(text)) {
    await writeFile(configPath, text.replace(/\[features\]/, '[features]\nhooks = true'), 'utf8')
    return `已在 ${configPath} 的 [features] 中加入 hooks = true`
  }
  await writeFile(configPath, `${text.trimEnd()}\n\n[features]\nhooks = true\n`, 'utf8')
  return `已在 ${configPath} 追加 [features].hooks = true`
}

async function readJson(path: string): Promise<Record<string, unknown>> {
  try {
    let text = await readFile(path, 'utf8')
    if (text.charCodeAt(0) === 0xfeff) text = text.slice(1)
    const parsed = JSON.parse(text) as unknown
    return parsed && typeof parsed === 'object' ? parsed as Record<string, unknown> : {}
  } catch (error) {
    const err = error as NodeJS.ErrnoException
    if (err.code === 'ENOENT') return {}
    throw new Error(`${path} 不是有效 JSON，已拒绝覆盖`)
  }
}

async function writeJson(path: string, value: unknown): Promise<void> {
  await mkdir(dirname(path), { recursive: true })
  await writeFile(path, `${JSON.stringify(value, null, 2)}\n`, 'utf8')
}

function asRecord(value: unknown): Record<string, unknown> {
  return value && typeof value === 'object' ? value as Record<string, unknown> : {}
}

function quoteArg(value: string): string {
  // Shell argument: quote when needed; do not double Windows path backslashes.
  if (!/[\s"$&'();<>|`]/.test(value)) return value
  return `"${value.replace(/"/g, '\\"')}"`
}
