import { spawn } from 'node:child_process'
import { mkdir, rm } from 'node:fs/promises'
import { homedir, platform } from 'node:os'
import { dirname, join } from 'node:path'
import { atomicWriteFile } from './atomic.js'
import { drainCmdPath, drainVbsPath, logPath, logsDir, observerNodePath, observerScriptPath } from './paths.js'

export async function installBootTasks(): Promise<string> {
  if (platform() === 'win32') return installWindowsTasks()
  if (platform() === 'darwin') return installMacTasks()
  return installLinuxTasks()
}

export async function uninstallBootTasks(): Promise<string> {
  if (platform() === 'win32') return uninstallWindowsTasks()
  if (platform() === 'darwin') return uninstallMacTasks()
  return uninstallLinuxTasks()
}

async function uninstallWindowsTasks(): Promise<string> {
  const names = ['SkillHub Observer Drain OnLogon', 'SkillHub Observer Drain Interval']
  const removed: string[] = []
  for (const name of names) {
    try {
      await run('schtasks', ['/Delete', '/TN', name, '/F'])
      removed.push(name)
    } catch {
      // task not registered
    }
  }
  try {
    await rm(drainCmdPath(), { force: true })
    await rm(drainVbsPath(), { force: true })
  } catch {
    // launchers already gone
  }
  return removed.length
    ? `已删除 Windows 计划任务: ${removed.join('、')}（并移除 drain 启动器）`
    : 'Windows 计划任务不存在，已跳过删除'
}

async function uninstallMacTasks(): Promise<string> {
  const plistPath = join(homedir(), 'Library', 'LaunchAgents', 'com.skillhub.observer.drain.plist')
  try {
    await run('launchctl', ['bootout', `gui/${process.getuid?.() || 501}`, plistPath])
  } catch {
    // not loaded
  }
  try {
    await rm(plistPath, { force: true })
    return `已卸载 macOS LaunchAgent: ${plistPath}`
  } catch {
    return `macOS LaunchAgent 不存在: ${plistPath}`
  }
}

async function uninstallLinuxTasks(): Promise<string> {
  const lines: string[] = []
  if (await hasCommand('systemctl')) {
    const unitDir = join(homedir(), '.config', 'systemd', 'user')
    const servicePath = join(unitDir, 'skillhub-observer-drain.service')
    const timerPath = join(unitDir, 'skillhub-observer-drain.timer')
    try {
      await run('systemctl', ['--user', 'disable', '--now', 'skillhub-observer-drain.timer'])
      lines.push('已禁用 Linux systemd timer: skillhub-observer-drain.timer')
    } catch {
      lines.push('Linux systemd timer 未启用，已跳过')
    }
    await rm(servicePath, { force: true })
    await rm(timerPath, { force: true })
    try {
      await run('systemctl', ['--user', 'daemon-reload'])
    } catch {
      // ignore
    }
  } else {
    let existing = ''
    try {
      existing = await capture('crontab', ['-l'])
    } catch {
      existing = ''
    }
    const kept = existing.split(/\r?\n/).filter((line) => line.trim() && !line.includes('skillhub-observer') && !line.includes('drain --reconcile'))
    if (kept.length !== existing.split(/\r?\n/).filter((line) => line.trim()).length) {
      await writeCrontab(kept.length ? `${kept.join('\n')}\n` : '')
      lines.push('已从用户 crontab 移除 Observer 条目')
    } else {
      lines.push('用户 crontab 中无 Observer 条目')
    }
  }
  return lines.join('；') || 'Linux 定时任务不存在，已跳过'
}

async function installWindowsTasks(): Promise<string> {
  await mkdir(dirname(drainCmdPath()), { recursive: true })
  const nodePath = observerNodePath()
  const scriptPath = observerScriptPath()
  // Manual/debug launcher
  const cmd = `@echo off\r\n"${nodePath}" "${scriptPath}" drain --reconcile\r\n`
  await atomicWriteFile(drainCmdPath(), cmd)
  // Silent launcher for Task Scheduler: no console window
  const vbsLines = [
    `' SkillHub Observer drain (hidden). Generated by install; do not edit by hand.`,
    `Set sh = CreateObject("Wscript.Shell")`,
    `cmd = """${nodePath}"" ""${scriptPath}"" drain --reconcile"`,
    `sh.Run cmd, 0, False`,
    ``
  ]
  await atomicWriteFile(drainVbsPath(), vbsLines.join('\r\n'))
  const taskTarget = `wscript.exe //B "${drainVbsPath()}"`
  await run('schtasks', ['/Create', '/TN', 'SkillHub Observer Drain OnLogon', '/SC', 'ONLOGON', '/RL', 'LIMITED', '/F', '/TR', taskTarget])
  await run('schtasks', ['/Create', '/TN', 'SkillHub Observer Drain Interval', '/SC', 'MINUTE', '/MO', '5', '/RL', 'LIMITED', '/F', '/TR', taskTarget])
  return `已注册 Windows 开机/每 5 分钟任务（无窗口），启动器 ${drainVbsPath()}`
}

async function installMacTasks(): Promise<string> {
  const plistPath = join(homedir(), 'Library', 'LaunchAgents', 'com.skillhub.observer.drain.plist')
  await mkdir(logsDir(), { recursive: true })
  const plist = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>com.skillhub.observer.drain</string>
  <key>ProgramArguments</key>
  <array>
    <string>${escapeXml(observerNodePath())}</string>
    <string>${escapeXml(observerScriptPath())}</string>
    <string>drain</string>
    <string>--reconcile</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>StartInterval</key>
  <integer>300</integer>
  <key>StandardOutPath</key>
  <string>${escapeXml(logPath())}</string>
  <key>StandardErrorPath</key>
  <string>${escapeXml(logPath())}</string>
</dict>
</plist>
`
  await mkdir(dirname(plistPath), { recursive: true })
  await atomicWriteFile(plistPath, plist)
  try {
    await run('launchctl', ['bootout', `gui/${process.getuid?.() || 501}`, plistPath])
  } catch {
    // not loaded yet
  }
  try {
    await run('launchctl', ['bootstrap', `gui/${process.getuid?.() || 501}`, plistPath])
  } catch {
    await run('launchctl', ['load', '-w', plistPath])
  }
  return `已注册 macOS LaunchAgent: ${plistPath}`
}

async function installLinuxTasks(): Promise<string> {
  if (await hasCommand('systemctl')) {
    const unitDir = join(homedir(), '.config', 'systemd', 'user')
    await mkdir(unitDir, { recursive: true })
    const servicePath = join(unitDir, 'skillhub-observer-drain.service')
    const timerPath = join(unitDir, 'skillhub-observer-drain.timer')
    const service = `[Unit]
Description=SkillHub Observer drain
[Service]
Type=oneshot
ExecStart=${quoted(observerNodePath())} ${quoted(observerScriptPath())} drain --reconcile
`
    const timer = `[Unit]
Description=SkillHub Observer drain timer
[Timer]
OnBootSec=30s
OnUnitActiveSec=5min
Persistent=true
[Install]
WantedBy=timers.target
`
    await atomicWriteFile(servicePath, service)
    await atomicWriteFile(timerPath, timer)
    await run('systemctl', ['--user', 'daemon-reload'])
    await run('systemctl', ['--user', 'enable', '--now', 'skillhub-observer-drain.timer'])
    return `已注册 Linux 用户 systemd timer: ${timerPath}`
  }
  const cronLine = `${quoted(observerNodePath())} ${quoted(observerScriptPath())} drain --reconcile`
  let existing = ''
  try {
    existing = await capture('crontab', ['-l'])
  } catch {
    existing = ''
  }
  const kept = existing.split(/\r?\n/).filter((line) => line.trim() && !line.includes('skillhub-observer') && !line.includes('drain --reconcile'))
  kept.push(`@reboot ${cronLine}`)
  kept.push(`*/5 * * * * ${cronLine}`)
  await writeCrontab(`${kept.join('\n')}\n`)
  return '当前环境没有 systemd，已写入用户 crontab（@reboot 与每 5 分钟）'
}

async function writeCrontab(text: string): Promise<void> {
  await new Promise<void>((resolve, reject) => {
    const child = spawn('crontab', ['-'], { stdio: ['pipe', 'ignore', 'pipe'] })
    let stderr = ''
    child.stderr.on('data', (chunk) => { stderr += String(chunk) })
    child.on('error', reject)
    child.on('close', (code) => {
      if (code === 0) resolve()
      else reject(new Error(stderr.trim() || `crontab 退出码 ${code}`))
    })
    child.stdin.end(text)
  })
}

async function hasCommand(name: string): Promise<boolean> {
  try {
    await run(platform() === 'win32' ? 'where' : 'which', [name])
    return true
  } catch {
    return false
  }
}

export type ScheduledRunner = (command: string, args: string[]) => Promise<string>

let scheduledRunner: ScheduledRunner = capture

export function setScheduledRunner(runner?: ScheduledRunner): void {
  scheduledRunner = runner || capture
}

export async function runScheduled(command: string, args: string[]): Promise<string> {
  return scheduledRunner(command, args)
}

async function run(command: string, args: string[]): Promise<void> {
  await runScheduled(command, args)
}

async function capture(command: string, args: string[]): Promise<string> {
  return await new Promise((resolve, reject) => {
    const child = spawn(command, args, { windowsHide: true })
    let stdout = ''
    let stderr = ''
    child.stdout.on('data', (chunk) => { stdout += String(chunk) })
    child.stderr.on('data', (chunk) => { stderr += String(chunk) })
    child.on('error', reject)
    child.on('close', (code) => {
      if (code === 0) resolve(stdout)
      else reject(new Error(stderr.trim() || stdout.trim() || `${command} 退出码 ${code}`))
    })
  })
}

function quoted(value: string): string {
  if (!/[ \t"]/.test(value)) return value
  return `"${value.replace(/"/g, '\\"')}"`
}

function escapeXml(value: string): string {
  return value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')
}
